default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ror_with_graphql_development
test:
  <<: *default
  database: ror_with_graphql_test

production:
  primary: &primary_production
    <<: *default
    database: ror_with_graphql_production
    username: ror_with_graphql
    password: <%= ENV["ROR_WITH_GRAPHQL_DATABASE_PASSWORD"] %>